config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :quizzs do
    member do
      post 'add_questions'
      get 'start'
      get 'play'
      post 'answer'
      get 'result'
    end
  end

  resources :questions, only: [:index, :show, :new, :create, :edit, :update, :destro] do
    member do
      get 'playshow'
      post 'check_answer'
    end
    collection do
      get 'index_perso'
    end 
  end

  get 'success', to: 'pages#success'
  get 'fail', to: 'pages#fail'
  
  devise_for :users, path: 'users'

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :quizz_flashcards, dependent: :destroy
  has_many :quizzs, through: :quizz_flashcards

  # validates :question, presence: true

  def correct_answers_array
    correct_answers.split(',').map(&:strip)
  end

  # Définir le champ correct_answers à partir d'un tableau
  def correct_answers_array=(values)
    self.correct_answers = values.join(',')
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only:[:show, :playshow, :check_answer]
  before_action :authenticate_user!, only: [:index, :index_perso, :new, :create]

  def new
    @question = current_user.questions.build
  end

  def show
    # @question = Question.find(params[:id])
  end

  def index
    @questions = Question.all
  end

  def index_perso
    @questions = current_user.questions
    @quizzs = current_user.quizzs
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to @question, notice: 'Question was successfully created.'
    else
      render :new
    end
  end

  def playshow
  end

  def check_answer
    selected_answers = params[:answers]
    
    correct_answers = @question.correct_answers_array

    if correct_answers.sort == selected_answers.sort
      redirect_to success_path, notice: 'Bonne réponse !'
    else
      redirect_to fail_path, alert: 'Mauvaise réponse. Essaie encore !'
    end
  end

  private

  def question_params
    params.require(:question).permit(:question, :answer1, :answer2, :answer3, :answer4, correct_answers_array: [])
  end

  def set_question
    @question = Question.find(params[:id])
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_card.html.erb
<div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="flip-card">
                    <div class="flip-card-inner">
                        <div class="flip-card-front">
                           <div class="card">
                                <div class="card-body-front-left">
                                    <div class="card-top-container">
                                        <div class="card-top-image"></div>
                                        <p>Thématique</p>
                                    </div>
                                    <div class="card-question-container">
                                        <h6 class="Thématique"><%= @question.question %></h6>
                                    </div>
                                    <div class="card-form-container">
                                        <%= form_with(url: check_answer_question_path(@question), local: true, method: :post, html: { style: 'width: 200px;' }) do |form| %>
                                        <p class="card-text">
                                            <ul class="card-checkbox-list">
                                                <li><%= form.check_box :answers, { multiple: true }, '1', nil %> <%= @question.answer1 %></li>
                                                <li><%= form.check_box :answers, { multiple: true }, '2', nil %> <%= @question.answer2 %></li>
                                                <li><%= form.check_box :answers, { multiple: true }, '3', nil %> <%= @question.answer3 %></li>
                                                <li><%= form.check_box :answers, { multiple: true }, '4', nil %> <%= @question.answer4 %></li>
                                                <li><%= form.check_box :answers, { multiple: true }, 'toutes', nil %> Toutes les réponses</li>
                                                <li><%= form.check_box :answers, { multiple: true }, 'aucunes', nil %> Aucune</li>
                                            </ul>
                                             <%= form.submit 'Valider', style: 'font-size: 11px; background-color: green; color: white; border: none; padding: 10px 20px; cursor: pointer;' %>
                                            <% end %>
                                        </p>
                                    </div>
                                </div>
                                <div class="card-body-front-right">
                                    <%# <div>
                                        <h5 class="card-title">foto</h5>
                                    </div> %>
                                </div>
                            </div>
                        </div>
                        <div class="flip-card-back">
                            <div class="card">
                                
                                <div class="card-body">
                                    <h5 class="card-title">Back Side</h5>
                                    <p class="card-text">React JS</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/index.html.erb
<div style="background-color: #f5f5f5; height: 500px; display: flex; justify-content: center; align-items: center;">
  <%# <%= link_to "Créer une question", new_question_path, class: "create-question-btn" %> 

  <ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.question, question_path(question) %> <%= link_to 'Jouer cette question', playshow_question_path(question), class: 'btn btn-primary' %></li>
  <% end %>
</ul>
</div>

app/views/questions/index_perso.html.erb
<div style="background-color: #f5f5f5; height: 500px; display: flex; justify-content: center; align-items: center;">
  <%# <%= link_to "Créer une question", new_question_path, class: "create-question-btn" %> 
<h3>Questions</h3>
  <ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.question, question_path(question) %> <%= link_to 'Jouer cette question', playshow_question_path(question), class: 'btn btn-primary' %></li>
  <% end %>
</ul>

<h3>Mes Quizzs</h3>
<ul>
  <% @quizzs.each do |quizz| %>
    <li><%= link_to quizz.title, quizz_path(quizz) %></li>
  <% end %>
</ul>
<%= link_to 'Créer un Nouveau Quizz', new_quizz_path, class: 'btn btn-primary' %>

</div>

app/views/questions/new.html.erb
<h1>Nouvelle question</h1>

<%= form_with(model: @question, url: questions_path, local: true) do |form| %>
  <div>
    <%= form.label :question %>
    <%= form.text_field :question %>
  </div>
  
  <div>
    <%= form.label :answer1 %>
    <%= form.text_field :answer1 %>
  </div>

  <div>
    <%= form.label :answer2 %>
    <%= form.text_field :answer2 %>
  </div>

  <div>
    <%= form.label :answer3 %>
    <%= form.text_field :answer3 %>
  </div>

  <div>
    <%= form.label :answer4 %>
    <%= form.text_field :answer4 %>
  </div>

  <div>
    <p>Select the correct answers:</p>
    <%= form.check_box :correct_answers_array, { multiple: true }, '1', nil %> 1
    <%= form.check_box :correct_answers_array, { multiple: true }, '2', nil %> 2
    <%= form.check_box :correct_answers_array, { multiple: true }, '3', nil %> 3
    <%= form.check_box :correct_answers_array, { multiple: true }, '4', nil %> 4
    <%= form.check_box :correct_answers_array, { multiple: true }, 'toutes', nil %> Toutes les réponses
    <%= form.check_box :correct_answers_array, { multiple: true }, 'aucunes', nil %> Aucune
  </div>

  <%= form.submit %>
<% end %>

app/views/questions/playshow.html.erb
<%= link_to "retour a l'index", questions_path %>

<%= render partial: 'questions/card', locals: { question: @question } %>

app/views/questions/show.html.erb
<h1>Question</h1>

<p>Question : <%= @question.question %></p>
<p>Réponse 1 : <%= @question.answer1 %></p>
<p>Réponse 2 : <%= @question.answer2 %></p>
<p>Réponse 3 : <%= @question.answer3 %></p>
<p>Réponse 4 : <%= @question.answer4 %></p>
<p>good answer : <%= @question.correct_answers %></p>

<%= link_to "retour a l'index", questions_path %>