config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :quizzs do
    member do
      post 'add_questions'
      get 'start'
      get 'play'
      post 'answer'
      get 'result'
    end
  end

  resources :questions, only: [:index, :show, :new, :create, :edit, :update, :destro] do
    member do
      get 'playshow'
      post 'check_answer'
    end
    collection do
      get 'index_perso'
    end 
  end

  get 'success', to: 'pages#success'
  get 'fail', to: 'pages#fail'
  
  devise_for :users, path: 'users'

end

app/models/quizz.rb
class Quizz < ApplicationRecord
  has_many :quizz_flashcards, dependent: :destroy
  has_many :questions, through: :quizz_flashcards

  belongs_to :user

  # validates :title, presence: true
end

app/controllers/quizzs_controller.rb
class QuizzsController < ApplicationController
  before_action :set_quizz, only: [:show, :start, :play, :answer, :result]
  def show
    @quizz = Quizz.find(params[:id])
    @questions = @quizz.questions
  end

  def index
  end

  def create
    @quizz = Quizz.new(quizz_params.except(:question_ids))
    @quizz.user = current_user
    if @quizz.save
      # Parcourir les question_ids pour créer des QuizzFlashcards
      question_ids = quizz_params["question_ids"].reject(&:blank?)
      question_ids.each do |question_id|
        question = Question.find_by(id: question_id)
        if question
          QuizzFlashcard.create(question: question, quizz: @quizz)
        end
      end

      puts "Quizz enregistré avec succès : #{@quizz.inspect}"
      redirect_to @quizz, notice: 'Quizz créé avec succès.'
    else
      puts "Erreur lors de la sauvegarde du Quizz : #{@quizz.errors.full_messages.join(", ")}"
      render :new
    end
  end

  def add_questions
    @quizz = Quizz.find(params[:id])
    question_ids = params[:question_ids].reject(&:blank?)
    question_ids.each do |question_id|
      question = Question.find_by(id: question_id)
      if question && !@quizz.questions.include?(question)
        @quizz.quizz_flashcards.create(question: question)
      end
    end
    redirect_to @quizz, notice: "Questions ajoutées avec succès."
  end

  def new
    @quizz = Quizz.new
  end

#la partie suivante sert a jouer les quizz
def start
  # Initialise l'état du quiz pour le début du jeu, stocké dans la session par exemple
  session[:quizz_question_ids] = @quizz.questions.pluck(:id)
  session[:current_question_index] = 0
  session[:correct_answers] = 0
  redirect_to play_quizz_path(@quizz)
end

def play
  puts "quizz: #{@quizz}"
  @current_index = session[:current_question_index] || 0
  question_ids = session[:quizz_question_ids]
  if @current_index >= question_ids.length
    redirect_to result_quizz_path(@quizz) and return
  end
  @question = Question.find(question_ids[@current_index])
end

# def answer
#   @current_index = session[:current_question_index]
#   question_ids = session[:quizz_question_ids]
#   @question = Question.find(question_ids[@current_index])

#   # Check the user's answer
#   if @question.correct_answers_array.include?(params[:answer])
#     session[:correct_answers] += 1
#   end

#   # Move to the next question
#   session[:current_question_index] += 1
#   redirect_to play_quizz_path(@quizz)
# end

def answer
  @current_index = session[:current_question_index]
  question_ids = session[:quizz_question_ids]
  @question = Question.find(question_ids[@current_index])

  # Évaluer la réponse de l'utilisateur
  if @question.correct_answers_array.include?(params[:answer])
    session[:correct_answers] += 1
  end

  # Passer à la question suivante
  session[:current_question_index] += 1
  if session[:current_question_index] < question_ids.length
    redirect_to play_quizz_path(@quizz)
  else
    redirect_to result_quizz_path(@quizz)
  end
end

def result
  @total_questions = session[:quizz_question_ids].length
  @correct_answers = session[:correct_answers]
  # Clear the session state
  session.delete(:quizz_question_ids)
  session.delete(:current_question_index)
  session.delete(:correct_answers)
end

private

def quizz_params
  params.require(:quizz).permit(:title, :description, question_ids: [])
end

def set_quizz
  @quizz = Quizz.find(params[:id])
end

end

app/helpers/quizzs_helper.rb
module QuizzsHelper
end

app/views/quizzs/create.html.erb
<h1>Quizzs#create</h1>
<p>Find me in app/views/quizzs/create.html.erb</p>

app/views/quizzs/index.html.erb
<h1>Quizzs#index</h1>
<p>Find me in app/views/quizzs/index.html.erb</p>

app/views/quizzs/new.html.erb
<%= form_for @quizz do |f| %>
  <div>
    <%= f.label :title, "Nom du Quizz" %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>
  </div>

 <div id="questions-container">
    <h3>Ajouter des questions</h3>
    
    <%= select_tag 'quizz[question_ids][]', 
          options_from_collection_for_select(current_user.questions, :id, :question),
          prompt: "Sélectionner des questions",
          multiple: true, 
          size: 10 %> <!-- Ajout d'une taille pour afficher plusieurs options à la fois -->
  </div>
  
  <div>
    <%= f.submit "Créer Quizz" %>
  </div>
<% end %>

app/views/quizzs/play.html.erb
<h2><%= @quizz.title %></h2>
<p>Question <%= session[:current_question_index] + 1 %> sur <%= session[:quizz_question_ids].size %></p>

<%= form_with url: answer_quizz_path(@quizz), method: :post, local: true do %>
  <p><%= @question.question %></p>
  
  <!-- Afficher les quatre propositions de réponse -->
  <div>
    <%= radio_button_tag :answer, "1" %>
    <%= label_tag "answer_1", @question.answer1 %>
  </div>
  <div>
    <%= radio_button_tag :answer, "2" %>
    <%= label_tag "answer_2", @question.answer2 %>
  </div>
  <div>
    <%= radio_button_tag :answer, "3" %>
    <%= label_tag "answer_3", @question.answer3 %>
  </div>
  <div>
    <%= radio_button_tag :answer, "4" %>
    <%= label_tag "answer_4", @question.answer4 %>
  </div>
  
  <%= submit_tag "Répondre" %>
<% end %>

app/views/quizzs/result.html.erb
<h2>Résultats du Quizz : <%= @quizz.title %></h2>
<p>Vous avez répondu correctement à <%= @correct_answers %> questions sur <%= @total_questions %>.</p>
<%= link_to 'Rejouer', start_quizz_path(@quizz) %>
<%= link_to 'Retour à la liste', quizzs_path %>

app/views/quizzs/show.html.erb
<h1><%="#{@quizz.title}"%></h1>
<p><%="#{@quizz.description}"%></p>


<h3>Questions associées</h3>
<ul>
  <% @questions.each do |question| %>
    <li><%= question.question %></li>
  <% end %>
</ul>

<h3>Ajouter des Questions</h3>
<%= form_with url: add_questions_quizz_path(@quizz), local: true do %>
  <div class="form-group">
    <%= label_tag 'questions_ids', 'Sélectionnez des questions' %>
    <%= select_tag 'question_ids[]', options_from_collection_for_select(Question.where.not(id: @quizz.questions.pluck(:id)), :id, :question), multiple: true, class: "form-control", size: 10 %>
  </div>
  <%= submit_tag "Ajouter", class: "btn btn-success" %>
<% end %>

<%= link_to 'Commencer le Quizz', start_quizz_path(@quizz), class: 'btn btn-primary' %>